---
development:
  API_URL:      http://localhost:9292/api/v1
  APP_URL:      http://localhost:3000
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token

test:
  API_URL:      http://localhost:9292/api/v1
  APP_URL:      http://localhost:3000

production:
  API_URL:      https://jablaydada-api.herokuapp.com/api/v1
  APP_URL:      https://jablaydada-app.herokuapp.com