---
development:
  APP_URL: http://localhost:3000
  API_URL: http://localhost:9292/api/v1

test:
  APP_URL: http://localhost:3000
  API_URL: http://localhost:9292/api/v1

production:
  API_URL: https://jablaydada-api.herokuapp.com/api/v1
  APP_URL: https://jablaydada-app.herokuapp.com