---
development:
  API_URL:              http://localhost:9292/api/v1
  APP_URL:              http://localhost:3000
  GH_OAUTH_URL:         https://github.com/login/oauth/authorize
  GH_TOKEN_URL:         https://github.com/login/oauth/access_token
  GH_SCOPE:             user:email
  GOOGLE_OAUTH_URL:     https://accounts.google.com/o/oauth2/auth
  GOOGLE_TOKEN_URL:     https://accounts.google.com/o/oauth2/token
  GOOGLE_REDIRECT_URI:  http://localhost:3000/auth/sso_callback/google_callback
  GOOGLE_SCOPE:         email

test:
  API_URL:              http://localhost:9292/api/v1
  APP_URL:              http://localhost:3000
  GH_OAUTH_URL:         https://github.com/login/oauth/authorize
  GH_TOKEN_URL:         https://github.com/login/oauth/access_token
  GH_SCOPE:             user:email
  GOOGLE_OAUTH_URL:     https://accounts.google.com/o/oauth2/auth
  GOOGLE_TOKEN_URL:     https://accounts.google.com/o/oauth2/token
  GOOGLE_REDIRECT_URI:  http://localhost:3000/auth/sso_callback/google_callback
  GOOGLE_SCOPE:         email, openid

production:
  API_URL:              https://jablaydada-api.herokuapp.com/api/v1
  APP_URL:              https://jablaydada-app.herokuapp.com
  GH_OAUTH_URL:         https://github.com/login/oauth/authorize
  GH_TOKEN_URL:         https://github.com/login/oauth/access_token
  GH_SCOPE:             user:email
  GOOGLE_OAUTH_URL:     https://accounts.google.com/o/oauth2/auth
  GOOGLE_TOKEN_URL:     https://accounts.google.com/o/oauth2/token
  GOOGLE_REDIRECT_URI:  https://jablaydada-app.herokuapp.com/auth/sso_callback/google_callback
  GOOGLE_SCOPE:         email